# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddtwoitemscrossoutoneanddeletethem():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addtwoitemscrossoutoneanddeletethem(self):
    self.driver.get("https://shopping-list-seven-kappa.vercel.app/")
    self.driver.set_window_size(945, 1020)
    self.driver.find_element(By.ID, "newItemTextbox").click()
    self.driver.find_element(By.ID, "newItemTextbox").send_keys("Pierwszy przedmiot")
    self.driver.find_element(By.ID, "newItemTextbox").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "newItemTextbox").click()
    self.driver.find_element(By.ID, "newItemTextbox").send_keys("Drugi przedmiot")
    self.driver.find_element(By.CSS_SELECTOR, ".gg-math-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-3xl:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
  
